package Vista;
import Modelo.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author SINAI DAYANARA M
 */
public class JInternalFrameAutores extends javax.swing.JInternalFrame {
    
    public JInternalFrameAutores() {
            initComponents();
            jTextIdAutor.setEnabled(false);
         } 
    public void limpiarCampos(){
        jTextIdAutor.setText("");
            jTextNombres.setText("");
            jTextApellidos.setText("");
            jTextEmail.setText("");
            jTextFechaNac.setText("");
    }
    public void obtenerDatos(){
    List<Autor> autores=new DAOAutor().ObtenerDatos();
    
    DefaultTableModel modelo= new DefaultTableModel();
    
    String[] columnas={"id_Autor","Nombres", "Apellidos",
    "Email","cedula", "FechaNac"};
    
    modelo.setColumnIdentifiers(columnas);
    for(Autor au:autores){
        String[]renglon={Integer.toString(au.getId_autor()),au.getCedula(),
          au.getNombres(),au.getApellidos(), au.getEmail(),
          au.getFechaNAC().toString()};
          modelo.addRow(renglon);
    }
    jTableAutor.setModel(modelo);
    }
    public void actualizarAutor(){
            int id=Integer.parseInt(this.jTextIdAutor.getText());
            String nom=this.jTextNombres.getText();
            String ape=this.jTextApellidos.getText();
            String corr=this.jTextEmail.getText();
            String ced=this.jTextCedula.getText();
            Date fec=Date.valueOf(this.jTextFechaNac.getText());
            
            DAOAutor dao=new DAOAutor();
            int res=dao.Actualizar(id, nom, ape, corr, ced, fec);
            if(res==1){
                JOptionPane.showMessageDialog(rootPane, "¡Autor actualizado!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "¡Ocurrio un error!");
            }
    }       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTransacciones = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTxtCampoDeTexto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelRYA = new javax.swing.JLabel();
        jLabel1id = new javax.swing.JLabel();
        jLabel2Nombres = new javax.swing.JLabel();
        jLabel3Apellidos = new javax.swing.JLabel();
        jLabel4Cedula = new javax.swing.JLabel();
        jLabel5FechNac = new javax.swing.JLabel();
        jLabel6Email = new javax.swing.JLabel();
        jTextIdAutor = new javax.swing.JTextField();
        jTextNombres = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jTextFechaNac = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutor = new javax.swing.JTable();
        jLabelRegistAutores = new javax.swing.JLabel();

        jLabelTransacciones.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTransacciones.setForeground(new java.awt.Color(51, 0, 206));
        jLabelTransacciones.setText("Transacciones");

        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(51, 0, 206));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(51, 0, 206));
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(51, 0, 206));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBorrar.setForeground(new java.awt.Color(51, 0, 206));
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(51, 0, 206));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTxtCampoDeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCampoDeTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtCampoDeTexto)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonActualizar))
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTransacciones)
                        .addGap(29, 29, 29)))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelTransacciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregar)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTxtCampoDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));

        jLabelRYA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRYA.setForeground(new java.awt.Color(51, 0, 206));
        jLabelRYA.setText("Registrar / Actualizar");

        jLabel1id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1id.setForeground(new java.awt.Color(51, 0, 206));
        jLabel1id.setText("ID");

        jLabel2Nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2Nombres.setForeground(new java.awt.Color(51, 0, 206));
        jLabel2Nombres.setText("Nombres");

        jLabel3Apellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3Apellidos.setForeground(new java.awt.Color(51, 0, 206));
        jLabel3Apellidos.setText("Apellidos");

        jLabel4Cedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4Cedula.setForeground(new java.awt.Color(51, 0, 206));
        jLabel4Cedula.setText("Cedula");

        jLabel5FechNac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5FechNac.setForeground(new java.awt.Color(51, 0, 206));
        jLabel5FechNac.setText("Fecha Nac");

        jLabel6Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6Email.setForeground(new java.awt.Color(51, 0, 206));
        jLabel6Email.setText("Email");

        jTextFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaNacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6Email)
                            .addComponent(jLabel2Nombres)
                            .addComponent(jLabel3Apellidos)
                            .addComponent(jLabel4Cedula)
                            .addComponent(jLabel5FechNac))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextApellidos)
                                .addComponent(jTextCedula)
                                .addComponent(jTextFechaNac)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                            .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1id)
                        .addGap(80, 80, 80)
                        .addComponent(jTextIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRYA)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRYA)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6Email)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1id)
                                            .addComponent(jTextIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2Nombres))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3Apellidos))
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4Cedula))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5FechNac))
                        .addGap(18, 18, 18)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTableAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableAutor);

        jLabelRegistAutores.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRegistAutores.setForeground(new java.awt.Color(51, 0, 206));
        jLabelRegistAutores.setText("Autores Registrados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabelRegistAutores)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRegistAutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int fila=this.jTableAutor.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de tabla");
        }
        else{
            int id=Integer.parseInt((String)this.jTableAutor.getValueAt(fila, 0).toString());
            DAOAutor dao=new DAOAutor();
            dao.Eliminar(id);
            obtenerDatos();
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        actualizarAutor();
        obtenerDatos();
        limpiarCampos();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jTextFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaNacActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
       //captura Datos de las cajas de texto
        String nomb=jTextNombres.getText();
        String apell=jTextApellidos.getText();
        String ema=jTextEmail.getText();
        String ced=jTextCedula.getText();
        String fecN=jTextFechaNac.getText();
        //comprueba que las cajas de texto no esten vacias
        if(nomb.contentEquals("")||apell.contentEquals("")||
                ema.contentEquals("")||ced.contentEquals("")||
                fecN.contentEquals("")){
                JOptionPane.showMessageDialog(rootPane, "TODOS los campos son obligatorios");
        }else{
        try{
            //convierte de String a Date
            Date fech=Date.valueOf(fecN);//Usar formato  de fecha: YYYY-mm-dd
            //objetopara acceder al metodo Insertar deDAOAutor
            Autor au=new DAOAutor().Insertar(ced, nomb, apell, ema, fech);
            JOptionPane.showMessageDialog(rootPane, "No se agrego el registro");
        }catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "No se agrego el registro");
        }
        }
        obtenerDatos();//llama a este metodo para que se muestre el nuevo
        //registro enn la tabla del formulario
        limpiarCampos();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTxtCampoDeTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCampoDeTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCampoDeTextoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int fila=this.jTableAutor.getSelectedRow();// Se obtiene #fila seleccionado
        if(fila==-1){
           JOptionPane.showMessageDialog(rootPane,"Seleccione un registro de la caja");
        }
        else{ 
            
            try{
            int id=Integer.parseInt((String)this.jTableAutor.getValueAt(fila, 0).toString());
            String nom=(String)this.jTableAutor.getValueAt(fila,1);
            String ape=(String)this.jTableAutor.getValueAt(fila,2);
            String corr=(String)this.jTableAutor.getValueAt(fila,3);
            String ced=(String)this.jTableAutor.getValueAt(fila,4);
            Date fec=Date.valueOf((String)this.jTableAutor.getValueAt(fila,5).toString());
            //Se ubican en las cajas de textos los datos capturados de la tabla
            jTextIdAutor.setText(""+id);
            jTextNombres.setText(nom);
            jTextApellidos.setText(ape);
            jTextEmail.setText(corr);
            jTextCedula.setText(ced);
            jTextFechaNac.setText(String.valueOf(fec));
            }catch(NumberFormatException e){
                 e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel1id;
    private javax.swing.JLabel jLabel2Nombres;
    private javax.swing.JLabel jLabel3Apellidos;
    private javax.swing.JLabel jLabel4Cedula;
    private javax.swing.JLabel jLabel5FechNac;
    private javax.swing.JLabel jLabel6Email;
    private javax.swing.JLabel jLabelRYA;
    private javax.swing.JLabel jLabelRegistAutores;
    private javax.swing.JLabel jLabelTransacciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAutor;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFechaNac;
    private javax.swing.JTextField jTextIdAutor;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTxtCampoDeTexto;
    // End of variables declaration//GEN-END:variables
}
